### ISSUE TITLE
Rewrite the registation form

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#1700]
Fields should be available in the registration according to [the discussion](https://github.com/oliverklee/ext-seminars/discussions/1376).

## My personal test URLs
- https://typo3-testing-10-4.ddev.site:8081/login
- https://typo3-testing-10-4.ddev.site:8081/2/registration?tx_seminars_eventregistration%5Bevent%5D=8&tx_seminars_pi1%5Baction%5D=register&tx_seminars_pi1%5Bseminar%5D=8&cHash=10fbb487968ba243e00c443770bd91fb

## ToDos

- [x] Guard: check by type and registration required
- [x] Guard: Check registration deadline & begin
- [x] error message if no registration is possible for this event
- [x] error message if no registration is possible now
- [x] 4 actions: new, confirm, create, thankYou (without validating the event model)
- [x] redirect to login page (with configuration) if no user is logged in and no onetimeaccount user ID is in the session
- [x] configuration for the salutation mode (and docs for installation + upgrade)
- [x] error message if the user already is registered
- [x] display the event, UID and date in the title
- [x] buttons to get forward from one page to the next
- [x] different button texts for free events and events with a cost
- [x] #1894
- [x] create registration with event + user on configured page
- [x] nice thank-you message on the last page
- [x] send emails
- [x] build the registration title
- [x] Drop the debugging alerts from the views
- [x] destroy the onetimeaccount session and log the user out
- [x] scalar fields
  - [x] `interests`
  - [x] `expectations`
  - [x] `backgroundKnowledge`
  - [x] `knownFrom`
  - [x] `comments`
  - [x] seats
  - [x] registered_themselves
  - [x] attendee's names
  - [x] billing address:
    - [x] separate billing address
    - [x] company
    - [x] name
    - [x] address
    - [x] zip
    - [x] city
    - [x] email
    - [x] country
    - [x] telephone
- [x] multiselects
  - [x] lodgings
  - [x] foods
  - [x] checkboxes
- [x] payment methods (hide if there are none, only display if there is only one)
- [x] price (drop-down for multiple, display for only one)
- [x] configuration for the currency (and docs for installation + upgrade)
- [x] display event, date, payment method & total price directly above the last button
- [x] terms 1 with page link
- [x] terms 2 with page link
- [ ] make some fields configurable

**Comment by oliverklee** [comment]
Notes on the billing address checkbox:
- The Bootstrap classes are `d-block` and `d-none`. We should name our classes correspondingly `tx-seminars-display-block` and `tx-seminars-display-none`.

**Comment by oliverklee** [comment]
`format.currency` VH: https://docs.typo3.org/other/typo3/view-helper-reference/10.4/en-us/typo3/fluid/latest/Format/Currency.html

**Comment by oliverklee** [comment]
Adding a validator: https://jweiland.net/typo3/beispiele-anleitungen-faq/extension-programmierung/extbase-dynamische-validierung.html
