### ISSUE TITLE
Rewrite the BE module

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#2034]
## Tasks (as per [the discussion](https://github.com/oliverklee/ext-seminars/discussions/1379))
- [x] Register the BE module with icon + title + permissions
- [x] layout + dummy template
- [x] dummy Controller for events
- [x] permissions
- [x] flash messages
- [x] provide access to the current PID
- [x] get events by PID (only single events and event dates) with sorting (highest start date on top), hidden events, but no deleted events
- [x] list events: UID, title, date
- [x] show icon (for the type and status (hidden etc.))
- [x] edit link for event
- [x] hide/unhide for events
- [x] show statistics: min, max, full, on waiting list, enough
- [x] CSV export of events
- [x] icons for "enough registrations" and "fully booked"
- [x] dummy Controller for registrations (and add the selected event to the debug information)
- [x] get regular registrations by event with sorting (newest on top)
- [x] get waiting list registrations by event with sorting (newest on top)
- [x] list registrations for an event: UID, user full name, seats, sorting: newest on top
- [x] registrations icons
- [x] edit link for registration
- [x] CSV export of registrations for an event (regular, waiting list)
- [x] maybe move the column with the icons around
- [x] email to the attendees of an event

## Docs
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/CreateModule.html
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/BackendModule/
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithExtbase/BackendModuleApiWithExtbase.html
https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/BackendModules/BackendModuleApi/Index.html
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.html

**Comment by oliverklee** [comment]
All done. Closing.
