### ISSUE TITLE
Add tests for the DataMapper sanitization/validation

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#450]
## Event records
- [x] #454 set the registration deadline to zero if it is > the begin date
https://github.com/oliverklee/ext-seminars/commit/ba8b7483e93c88d1eba8faaa7ec586afda78c433
- [x] #456 set the early-bird deadline to zero if it is > the begin date https://github.com/oliverklee/ext-seminars/commit/51e3a31294f98baccb302dceca60215d15a5662e
- [x] #455 set the regular early-bird price to 0 if is is higher than the regular price https://github.com/oliverklee/ext-seminars/commit/51e3a31294f98baccb302dceca60215d15a5662e
- [x] #455 set the special early-bird price to 0 if is is higher than the special price
https://github.com/oliverklee/ext-seminars/commit/51e3a31294f98baccb302dceca60215d15a5662e
- [x] ~update the statistics https://github.com/oliverklee/ext-seminars/commit/42a6fc5f6fd0c77691c4f80d4ee00d651e14e234~ (removed in 70b52170557ed40a660bcab4e178c32cce7c9c70)
- [x] stuff from [Event::getUpdateArray](https://github.com/oliverklee/ext-seminars/blob/master/Classes/OldModel/Event.php#L170):
  - [x] #462 get/update the begin date from the time slots
  - [x] #462 get/update the end date from the time lots
  - [x] #471get/update the places from the time slots

## Time slots
- [x] #451 set the title from the begin date (may also be possible using TCA instead)
